sudo: false
language: node_js
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
cache: npm
install:
  - npm install
script:
  - npm test
jobs:
  include:
    - stage: release
      if: branch = master AND type != pull_request
      node_js: "10"
      script:
        - npx semantic-release
branches:
  only:
    - master
notifications:
  email: false
